import { v4 as uuidv4 } from 'uuid';

const USER_ID_KEY = 'i2e_search_uid';

/**
 * Get or create anonymous user ID from localStorage
 */
export function getUserId(): string {
  if (typeof window === 'undefined') {
    return '';
  }
  
  let userId = localStorage.getItem(USER_ID_KEY);
  
  if (!userId) {
    userId = uuidv4();
    localStorage.setItem(USER_ID_KEY, userId);
  }
  
  return userId;
}

/**
 * Format time ago string
 */
export function formatTimeAgo(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  
  if (diffDays === 0) {
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    if (diffHours === 0) {
      const diffMins = Math.floor(diffMs / (1000 * 60));
      return diffMins <= 1 ? 'Just now' : `${diffMins} minutes ago`;
    }
    return diffHours === 1 ? '1 hour ago' : `${diffHours} hours ago`;
  } else if (diffDays < 7) {
    return diffDays === 1 ? '1 day ago' : `${diffDays} days ago`;
  } else if (diffDays < 30) {
    const weeks = Math.floor(diffDays / 7);
    return weeks === 1 ? '1 week ago' : `${weeks} weeks ago`;
  } else if (diffDays < 365) {
    const months = Math.floor(diffDays / 30);
    return months === 1 ? '1 month ago' : `${months} months ago`;
  } else {
    const years = Math.floor(diffDays / 365);
    return years === 1 ? '1 year ago' : `${years} years ago`;
  }
}

/**
 * Highlight text with search query
 */
export function highlightText(text: string, query: string): string {
  if (!query || !text) return text;
  
  const regex = new RegExp(`(${query})`, 'gi');
  return text.replace(regex, '<mark>$1</mark>');
}

/**
 * Get snippet from text
 */
export function getSnippet(text: string, maxLength: number = 150): string {
  if (!text) return '';
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength).trim() + '...';
}

/**
 * Display content summary (AI-generated, stored in database)
 * Content is already generated by AI during scraping, just display it directly
 */
export function generateTwoLineSummary(content: string, pageDescription?: string): string {
  // Content field already contains AI-generated summary from scraper
  // Just return it directly, no processing needed
  if (content && content.trim().length > 0) {
    return content.trim();
  }
  
  // Fallback to description if content is empty
  if (pageDescription && pageDescription.trim().length > 0) {
    // If no content but we have page_description, extract first 3 sentences as fallback
    const sentenceRegex = /[^.!?]*[.!?]+(?:\s+|$)/g;
    const sentences = pageDescription.match(sentenceRegex) || [];
    if (sentences.length >= 3) {
      return sentences.slice(0, 3).join(' ').trim();
    }
    // Fallback to first 300 chars
    return pageDescription.length > 300 
      ? pageDescription.substring(0, 300).trim() + '...'
      : pageDescription.trim();
  }
  
  return '';
}
